kind: ConfigMap
apiVersion: v1
metadata:
  name: prestocluster-sample-coordinator-config
  namespace: presto-system
  labels:
    app: prestocluster-sample
data:
  config.properties: |-
    node.environment=test
    coordinator=true
    http-server.http.port=8080
    discovery-server.enabled=true
    discovery.uri=http://localhost:8080
    node-scheduler.include-coordinator=true
    query.max-memory=2GB
  jvm.config: |-
    -server
    -XX:+UseG1GC
    -Xmx1G
    -Djdk.attach.allowAttachSelf=true
  node.properties: |-
    node.environment=test
    node.data-dir=/opt/presto/data
  tpcds: |-
    connector.name=tpcds
  hive: |-
    cache.alluxio.max-cache-size=1GB
    cache.base-directory=file:///tmp/alluxio
    cache.enabled=true
    cache.type=ALLUXIO
    connector.name=hive-hadoop2
    hive.metastore.uri=thrift://172.17.195.73:9083
    hive.node-selection-strategy=SOFT_AFFINITY
