apiVersion: v1
kind: Pod
metadata:
  name: juicefs-redis-minio
#  namespace: bigdata-dev
  labels:
    app: juicefs-redis-minio
spec:
  containers:
    - name: juicefs-redis-minio
      securityContext:
        privileged: true
      image: registry.mufankong.top/bigdata/juicefs-mysql-minio:1.0.0-rc2-v2
      imagePullPolicy: IfNotPresent
      env:
        - name: META_URL
          value: "redis://:123456@redis-01:6379/1"
        - name: STORAGE
          value: "minio"
        - name: BUCKET
          value: "http://minio-01:9000/myjfs2"
        - name: ACCESS_KEY
          value: "minio"
        - name: SECRET_KEY
          value: "minio123"
---
apiVersion: v1
kind: Service
metadata:
  name: juicefs-redis-minio-svc
#  namespace: bigdata-dev
spec:
  selector:
    app: juicefs-redis-minio
  ports:
    - name: web-ui
      port: 9100

