apiVersion: v1
kind: Pod
metadata:
  name: juicefs-mysql-minio
#  namespace: bigdata-dev
  labels:
    app: juicefs-mysql-minio
spec:
  containers:
    - name: juicefs-mysql-minio
      securityContext:
        privileged: true
      image: registry.mufankong.top/bigdata/juicefs-mysql-minio:1.0.0-rc2-v2
      imagePullPolicy: IfNotPresent
      env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: META_URL
          value: "mysql://root:bigdata@(10.81.17.8:33066)/juicefs_k8s"
        - name: STORAGE
          value: "minio"
        - name: BUCKET
          value: "http://minio-01:9000/myjfs"
        - name: ACCESS_KEY
          value: "minio"
        - name: SECRET_KEY
          value: "minio123"
---
apiVersion: v1
kind: Service
metadata:
  name: juicefs-mysql-minio-svc
#  namespace: bigdata-dev
spec:
  selector:
    app: juicefs-mysql-minio
  ports:
    - name: web-ui
      port: 9100

