# Service to access the yarn web ui
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hadoop.fullname" . }}-hdfs-ui
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
    component: hdfs-ui
spec:
  ports:
  - port: 50070
    name: web
  selector:
    app: {{ include "hadoop.name" . }}
    component: hdfs-nn
