#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Docker image with JDK/MYSQL/DORIS installed
FROM centos:7.9.2009

ENV DORIS_VERSION 0.14.13.1

ENV DORIS_HOME /home/admin/PALO-$DORIS_VERSION-release-binary
ENV JAVA_HOME /home/admin/jdk1.8.0_141
ENV MVN_HOME /home/admin/apache-maven-3.6.1
ENV PATH $PATH:$JAVA_HOME/bin:$MVN_HOME/bin

USER root

WORKDIR /home/admin

# install tools
RUN yum -y install lsof.x86_64 wget.x86_64 tar.x86_64 git.x86_64 which.x86_64 net-tools.x86_64  unzip.x86_64 numactl libaio   perl net-tools

#install mysql
RUN wget https://cdn.mysql.com//Downloads/MySQL-5.7/mysql-5.7.37-1.el7.x86_64.rpm-bundle.tar \
    && tar -xvf mysql-5.7.37-1.el7.x86_64.rpm-bundle.tar \
    && rpm -ivh mysql-community-common-5.7.37-1.el7.x86_64.rpm \
    && rpm -ivh mysql-community-libs-5.7.37-1.el7.x86_64.rpm \
    && rpm -ivh mysql-community-client-5.7.37-1.el7.x86_64.rpm && rpm -ivh mysql-community-server-5.7.37-1.el7.x86_64.rpm


# install mvn
RUN wget https://archive.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz \
    && tar -zxvf apache-maven-3.6.1-bin.tar.gz \
    && rm -f apache-maven-3.6.1-bin.tar.gz
COPY conf/maven/settings.xml $MVN_HOME/conf/settings.xml


# setup jdk
RUN wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u141-b15/336fa29ff2bb4ef291e347e091f7f4a7/jdk-8u141-linux-x64.tar.gz" \
    && tar -zxvf /home/admin/jdk-8u141-linux-x64.tar.gz \
    && rm -f /home/admin/jdk-8u141-linux-x64.tar.gz



# # setup doris
RUN wget https://palo-cloud-repo-bd.bd.bcebos.com/baidu-doris-release/PALO-$DORIS_VERSION-release-binary.tar.gz \
    && tar -zxvf /home/admin/PALO-$DORIS_VERSION-release-binary.tar.gz \
    && rm -f /home/admin/PALO-$DORIS_VERSION-release-binary.tar.gz \
     && mkdir -p /data/doris/storage && mkdir -p /data/doris/doris-meta
COPY conf/doris/fe.conf $DORIS_HOME/fe/conf
COPY conf/doris/be.conf $DORIS_HOME/be/conf


COPY ./entrypoint_doris.sh /home/admin/entrypoint_doris.sh
RUN chmod u+x /home/admin/entrypoint_doris.sh

ENTRYPOINT ["/home/admin/entrypoint_doris.sh"]
