FROM dolphinscheduler.docker.scarf.sh/apache/dolphinscheduler-tools:3.0.0-beta-2
# For example
# FROM dolphinscheduler.docker.scarf.sh/apache/dolphinscheduler-tools:3.0.0-beta-2

COPY mysql-connector-java-8.0.21.jar /opt/dolphinscheduler/tools/libs/mysql-connector-java-8.0.21.jar
