apiVersion: v1
kind: Pod
metadata:
  name: hadoop-spark-client
  labels:
    app:  hadoop-spark-client
spec:
  containers:
    - name: client
      image: registry.mufankong.top/bigdata/hadoop-spark-client:h2.7.2-s3.2.1
      imagePullPolicy: IfNotPresent
      env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: HADOOP_CONF_DIR
          value: /opt/hadoop_conf
      volumeMounts:
        - name: spark-conf
          mountPath: /opt/spark-3.2.1-bin-hadoop2.7/conf/spark-defaults.conf
          subPath: spark-defaults.conf
        - name: hadoop-conf
          mountPath: /opt/spark-3.2.1-bin-hadoop2.7/conf/core-site.xml
          subPath: core-site.xml
        - name: hadoop-conf
          mountPath: /opt/spark-3.2.1-bin-hadoop2.7/conf/yarn-site.xml
          subPath: yarn-site.xml
        - name: hadoop-conf
          mountPath: /opt/spark-3.2.1-bin-hadoop2.7/conf/hive-site.xml
          subPath: hive-site.xml
        - name: hadoop-conf
          mountPath: /opt/spark-3.2.1-bin-hadoop2.7/conf/mapred-site.xml
          subPath: mapred-site.xml
        - name: hadoop-conf
          mountPath: /opt/hadoop_conf
  volumes:
    - name: spark-conf
      configMap:
        name: spark-conf-map
    - name: hadoop-conf
      configMap:
        name: spark-hadoop-conf-map

---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-spark-client
spec:
  selector:
    app: hadoop-spark-client
  clusterIP: None




