apiVersion: v1
kind: Pod
metadata:
  name: hadoop-client
  namespace: bigdata-dev
  labels:
    app:  hadoop-client
spec:
  containers:
    - name: client
      image: registry.mufankong.top/bigdata/danisla/hadoop-client:2.7.2
      imagePullPolicy: IfNotPresent
      envFrom:
        - configMapRef:
            name: hadoop-env
      volumeMounts:
        - name: hadoop-conf
          mountPath: /opt/hadoop-conf/
# todo 增加headless 使client模式能找到提交的节点， 增加env HADOOP_CONF_DIR
  volumes:
    - name: hadoop-conf
      configMap:
        name: hadoop-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hadoop-env
  namespace: bigdata-dev
data:
  HADOOP_CONF_DIR: /opt/hadoop-conf/
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-client
  namespace: bigdata-dev
spec:
  selector:
    app: hadoop-client
  clusterIP: None

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hadoop-conf
  namespace: bigdata-dev
data:
  core-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
      <property>
            <name>fs.defaultFS</name>
            <value>jfs://myjfs</value>
            <description>NameNode URI</description>
        </property>
      <property>
             <name>fs.jfs.impl</name>
             <value>io.juicefs.JuiceFileSystem</value>
         </property>
         <property>
             <name>fs.AbstractFileSystem.jfs.impl</name>
             <value>io.juicefs.JuiceFS</value>
         </property>
         <property>
             <name>juicefs.meta</name>
             <value>mysql://root:eWJmP7yvpccHCtmVb61Gxl2XLzIrRgmT@(mysql-01:3306)/juicefs2_meta_minio</value>
         </property>
         <property>
             <name>juicefs.cache-size</name>
             <value>1024</value>
         </property>
         <property>
             <name>juicefs.access-log</name>
             <value>/tmp/juicefs.access.log</value>
         </property>
         <property>
             <name>juicefs.cache-dir</name>
             <value>/tmp/data/juicefs</value>
         </property>
    </configuration>


  yarn-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>

    <configuration>
      <property>
        <name>yarn.resourcemanager.hostname</name>
        <value>bigdata-hadoop-yarn-rm</value>
      </property>

      <!-- Bind to all interfaces -->
      <property>
        <name>yarn.resourcemanager.bind-host</name>
        <value>0.0.0.0</value>
      </property>
      <property>
        <name>yarn.nodemanager.bind-host</name>
        <value>0.0.0.0</value>
      </property>
      <property>
        <name>yarn.timeline-service.bind-host</name>
        <value>0.0.0.0</value>
      </property>
      <!-- /Bind to all interfaces -->

      <property>
        <name>yarn.nodemanager.vmem-check-enabled</name>
        <value>false</value>
      </property>

      <property>
        <name>yarn.nodemanager.aux-services</name>
        <value>mapreduce_shuffle</value>
      </property>

      <property>
        <name>yarn.nodemanager.aux-services.mapreduce_shuffle.class</name>
        <value>org.apache.hadoop.mapred.ShuffleHandler</value>
      </property>

      <property>
        <description>List of directories to store localized files in.</description>
        <name>yarn.nodemanager.local-dirs</name>
        <value>/var/lib/hadoop-yarn/cache/${user.name}/nm-local-dir</value>
      </property>

      <property>
        <description>Where to store container logs.</description>
        <name>yarn.nodemanager.log-dirs</name>
        <value>/var/log/hadoop-yarn/containers</value>
      </property>

      <property>
        <description>Where to aggregate logs to.</description>
        <name>yarn.nodemanager.remote-app-log-dir</name>
        <value>/var/log/hadoop-yarn/apps</value>
      </property>

      <property>
        <name>yarn.application.classpath</name>
        <value>
          /usr/local/hadoop/etc/hadoop,
          /usr/local/hadoop/share/hadoop/common/*,
          /usr/local/hadoop/share/hadoop/common/lib/*,
          /usr/local/hadoop/share/hadoop/hdfs/*,
          /usr/local/hadoop/share/hadoop/hdfs/lib/*,
          /usr/local/hadoop/share/hadoop/mapreduce/*,
          /usr/local/hadoop/share/hadoop/mapreduce/lib/*,
          /usr/local/hadoop/share/hadoop/yarn/*,
          /usr/local/hadoop/share/hadoop/yarn/lib/*
        </value>
      </property>
    </configuration>


  mapred-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>

    <configuration>
    	<property>
            <name>mapreduce.framework.name</name>
            <value>yarn</value>
        </property>
        <property>
              <name>mapreduce.map.memory.mb</name>
              <value>5120</value>
        </property>
        <property>
              <name>mapreduce.reduce.memory.mb</name>
              <value>5120</value>
        </property>
    </configuration>

