apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-history
  labels:
    app:  spark-history
spec:
  replicas: 1
  serviceName: spark-history-service
  selector:
    matchLabels:
      app:  spark-history
  template:
    metadata:
      labels:
        app:  spark-history
    spec:
      containers:
        - name: spark-history
          image: registry.mufankong.top/bigdata/hadoop-spark-client:h2.7.2-s3.2.1
          imagePullPolicy: IfNotPresent
          # todo 增加Fair调度和executor num，服务监控检查
          command: [ "/bin/sh","-c","/usr/local/hadoop-2.7.2/bin/hadoop fs -mkdir -p /spark3/history ; /opt/spark-3.2.1-bin-hadoop2.7/sbin/start-history-server.sh  ;  tail -f /opt/spark-3.2.1-bin-hadoop2.7/logs/spark--org.apache.spark.deploy.history.HistoryServer-1-$MY_POD_NAME.out; " ]
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HADOOP_CONF_DIR
              value: /opt/hadoop_conf
          volumeMounts:
            - name: spark-conf
              mountPath: /opt/spark-3.2.1-bin-hadoop2.7/conf/spark-defaults.conf
              subPath: spark-defaults.conf
            - name: hadoop-conf
              mountPath: /opt/spark-3.2.1-bin-hadoop2.7/conf/core-site.xml
              subPath: core-site.xml
            - name: hadoop-conf
              mountPath: /opt/spark-3.2.1-bin-hadoop2.7/conf/yarn-site.xml
              subPath: yarn-site.xml
            - name: hadoop-conf
              mountPath: /opt/spark-3.2.1-bin-hadoop2.7/conf/hive-site.xml
              subPath: hive-site.xml
            - name: hadoop-conf
              mountPath: /opt/spark-3.2.1-bin-hadoop2.7/conf/mapred-site.xml
              subPath: mapred-site.xml
            - name: hadoop-conf
              mountPath: /opt/hadoop_conf
      volumes:
        - name: spark-conf
          configMap:
            name: spark-conf-map
        - name: hadoop-conf
          configMap:
            name: spark-hadoop-conf-map

---
apiVersion: v1
kind: Service
metadata:
  name: spark-history-svc
spec:
  ports:
    - port: 18080
      protocol: TCP
      name: spark-history-web
  selector:
    # same of pod label
    app: spark-history
---
kind: Service
apiVersion: v1

metadata:
  name: spark-history-service
  labels:
    app: spark-history
spec:
  selector:
    app: spark-history
  clusterIP: None
  type: ClusterIP

