# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: bigdata-hadoop-yarn-rm
  labels:
    app: hadoop
    release: bigdata
    component: yarn-rm
spec:
  ports:
  - port: 8088
    name: web
  - port: 8032
    name: rpc
  clusterIP: None
  selector:
    app: hadoop
    component: yarn-rm
    release: bigdata
