kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: bigdata-hadoop-yarn-nm
  labels:
    app: hadoop
    component: yarn-nm
    release: bigdata

spec:
  replicas: 3
  volumeClaimTemplates:
    - metadata:
        name: nn-local-dir
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 300Gi
  selector:
    matchLabels:
      app: hadoop
      component: yarn-nm
      release: bigdata
  template:
    metadata:
      labels:
        app: hadoop
        component: yarn-nm
        release: bigdata
    spec:
      volumes:
        - name: jmx-config
          configMap:
              name: jmx-configmap
        - name: hadoop-config
          configMap:
            name: bigdata-hadoop
      containers:
        - name: jmx-exporter
          env:
            - name: SERVICE_PORT
              value: "8007"
          image: "registry.mufankong.top/bigdata/jmx-prometheus-exporter:0.12.0-openjdk"
          imagePullPolicy: Always
          ports:
            - name: metrics
              containerPort: 8007
          volumeMounts:
            - name: jmx-config
              mountPath: /opt/jmx_exporter/config.yml
              subPath: yarn-nodemanager-config.yml
          livenessProbe:
            failureThreshold: 8
            httpGet:
              path: /metrics
              port: 8007
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 60
          readinessProbe:
            failureThreshold: 8
            httpGet:
              path: /metrics
              port: 8007
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 60
        - name: yarn-nm
          image: 'registry.mufankong.top/bigdata/poker/hadoop:2.7.2'
          command:
            - /bin/bash
            - /tmp/hadoop-config/bootstrap.sh
            - '-d'
          ports:
            - name: web
              containerPort: 8088
              protocol: TCP
          env:
            - name: MY_CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: yarn-nm
                  resource: limits.cpu
                  divisor: '1'
            - name: MY_MEM_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: yarn-nm
                  resource: limits.memory
                  divisor: 1M
            - name: TZ
              value: "Asia/Shanghai"
          resources:
            limits:
              cpu: '4'
              memory: 8Gi
            requests:
              cpu: '2'
              memory: 8Gi
          volumeMounts:
            - name: hadoop-config
              mountPath: /tmp/hadoop-config
            - name: nn-local-dir
              mountPath: /var/lib/hadoop-yarn/cache/root/nm-local-dir
          livenessProbe:
            httpGet:
              path: /node
              port: 8042
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /node
              port: 8042
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 2
          imagePullPolicy: Always
      terminationGracePeriodSeconds: 0
      securityContext: {}
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#              - matchExpressions:
#                  - key: small_storage
#                    operator: DoesNotExist

  serviceName: bigdata-hadoop-yarn-nm

