apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: doris-be
  labels:
    app: doris-be
spec:
  replicas: 3
  volumeClaimTemplates:
    - metadata:
        name: pvc-doris-be
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 300Gi
  serviceName: doris-be-service
  selector:
    matchLabels:
      app: doris-be
  template:
    metadata:
      labels:
        app: doris-be
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: doris-be
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: BE_IPADDRESS
              valueFrom:
                 fieldRef:
                   fieldPath: status.podIP
          image: registry.mufankong.top/bigdata/zhaomin1423/doris-be:1.0.0
          command: [ "/bin/bash", "-ce", "/opt/doris/doris-be-1.0.0/be/bin/start_be.sh" ]
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8040
            initialDelaySeconds: 300
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3            
          ports:
            - containerPort: 9060
              protocol: TCP
            - containerPort: 9070
              protocol: TCP
            - containerPort: 8040
              protocol: TCP
            - containerPort: 9050
              protocol: TCP
            - containerPort: 8060
              protocol: TCP
          resources:
            limits:
              cpu: 2
              memory: 2G
            requests:
              cpu: 200m
              memory: 1G
          volumeMounts:
            - mountPath: /opt/doris/doris-be-1.0.0/be/storage
              name: pvc-doris-be



---
kind: Service
apiVersion: v1

metadata:
  name: doris-be-service
  labels:
    app: doris-be
spec:
  selector:
    app: doris-be
  clusterIP: None
  type: ClusterIP
