FROM ubuntu:trusty

RUN apt-get install mysql-client curl tar -y

COPY apache-doris-be-1.1.2-bin-x86_64.tar.gz /opt/apache-doris-be-1.1.2-bin-x86_64.tar.gz
RUN tar zxvf /opt/apache-doris-be-1.1.2-bin-x86_64.tar.gz -C /opt/
RUN rm -rf  /opt/doris/apache-doris-be-1.1.2-bin-x86_64.tar.gz
RUN  ln -s /opt/apache-doris-be-1.1.2-bin-x86_64 /opt/doris

EXPOSE 9060
EXPOSE 8040
EXPOSE 9050
EXPOSE 8060

COPY  register_be.sh /opt/register_be.sh
COPY  decommision_be.sh /opt/decommision_be.sh
RUN chmod  +x /opt/register_be.sh
RUN chmod  +x /opt/decommision_be.sh

CMD /opt/doris/be/bin/start_be.sh