FROM ubuntu:trusty

ADD jdk-8u333-linux-x64.tar.gz /opt/jdk
ADD doris-fe-1.0.0.tar.gz /opt/doris

ENV JAVA_HOME /opt/jdk/jdk1.8.0_333
ENV CLASSPATH $JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
ENV PATH $PATH:$JAVA_HOME/bin

RUN apt-get install mysql-client curl -y

#HEALTHCHECK --interval=5s --timeout=3s --retries=10 \
#    CMD curl -f http://127.0.0.1:8030/api/bootstrap || exit 1

EXPOSE 8030
EXPOSE 9020
EXPOSE 9030
EXPOSE 9010

CMD /opt/doris/doris-fe-1.0.0/fe/bin/start_fe.sh