FROM ubuntu:trusty

ADD jdk-8u333-linux-x64.tar.gz /opt/jdk
ADD doris-be-1.0.0.tar.gz /opt/doris
#ADD entrypoint.sh /opt
#ADD backends_check.sh /opt

ENV JAVA_HOME /opt/jdk/jdk1.8.0_333
ENV CLASSPATH $JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
ENV PATH $PATH:$JAVA_HOME/bin

RUN apt-get install mysql-client curl -y


#HEALTHCHECK --interval=3s --timeout=15s --retries=10 \
#    CMD /bin/bash /opt/backends_check.sh || exit 1

EXPOSE 9060
EXPOSE 8040
EXPOSE 9050
EXPOSE 8060

CMD /opt/doris/doris-be-1.0.0/be/bin/start_be.sh