apiVersion: v1
kind: ConfigMap
metadata:
  name: hadoop-env
  namespace: k8s-bigdata
data:
  YARN_CONF_yarn_log_server_url: https://historyserver:8188/applicationhistory/logs/
  YARN_CONF_yarn_resourcemanager_hostname: resourcemanager
  YARN_CONF_yarn_resourcemanager_address: resourcemanager:8032
  YARN_CONF_yarn_resourcemanager_scheduler_address: resourcemanager:8030
  YARN_CONF_yarn_resourcemanager_resource__tracker_address: resourcemanager:8031
  YARN_CONF_yarn_timeline___service_hostname: historyserver
  MAPRED_CONF_mapred_child_java_opts: "-Xmx4096m"
  MAPRED_CONF_mapreduce_jobhistory_address: historyserver:10020
  MAPRED_CONF_mapreduce_jobhistory_webapp_address: historyserver:19888
  SPARK_NUM_CORES: "2"
  SPARK_DRIVER_MEMORY: "32g"
  CORE_CONF_fs_defaultFS: "hdfs://namenode:9000"
  SPARK_MASTER: "spark://namenode:7077"
  HADOOP_URL: "hdfs://namenode:9000"
