apiVersion: v1
kind: Service
metadata:
  name: datanode
  namespace: k8s-bigdata
spec:
  selector:
    app: datanode
  clusterIP: None
  ports:
    - name: datanode-ipc
      port: 9864
      targetPort: 9864
