apiVersion: v1
kind: Pod
metadata:
  name: namenode
  namespace: k8s-bigdata
  labels:
    app: namenode
spec:
  volumes:
    - name: vol
  containers:
    - name: namenode
      image: vpemfh7/hadoop-namenode
      imagePullPolicy: IfNotPresent
      envFrom:
        - configMapRef:
            name: hadoop-env
      ports:
        - containerPort: 9870
        - containerPort: 9000
        - containerPort: 9866
        - containerPort: 8080
        - containerPort: 7077
        - containerPort: 6066
      volumeMounts:
        - name: vol
          mountPath: /hadoop/dfs/name
