apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-cfg
  labels:
    app: hive
data:
  core-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
      <property>
            <name>fs.defaultFS</name>
            <value>jfs://myjfs</value>
        </property>
       <property>
          <name>fs.jfs.impl</name>
          <value>io.juicefs.JuiceFileSystem</value>
      </property>
      <property>
          <name>fs.AbstractFileSystem.jfs.impl</name>
          <value>io.juicefs.JuiceFS</value>
      </property>
      <property>
          <name>juicefs.meta</name>
          <value>mysql://root:eWJmP7yvpccHCtmVb61Gxl2XLzIrRgmT@(mysql-01:3306)/juicefs2_meta_minio</value>
      </property>
      <property>
          <name>juicefs.cache-size</name>
          <value>1024</value>
      </property>
      <property>
          <name>juicefs.access-log</name>
          <value>/tmp/juicefs.access.log</value>
      </property>
      <property>
          <name>juicefs.cache-dir</name>
          <value>/tmp/data/juicefs</value>
      </property>

      </configuration>

  hive-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
        <configuration>

          <property><name>hive.metastore.uris</name><value>thrift://hive-metastore-service:9083</value></property>
          <property><name>datanucleus.autoCreateSchema</name><value>false</value></property>
          <property><name>javax.jdo.option.ConnectionURL</name><value>jdbc:mysql://mysql-01/hive2_3_9?useSSL=false</value></property>
          <property><name>javax.jdo.option.ConnectionDriverName</name><value>com.mysql.jdbc.Driver</value></property>
          <property><name>javax.jdo.option.ConnectionPassword</name><value>eWJmP7yvpccHCtmVb61Gxl2XLzIrRgmT</value></property>
          <property><name>javax.jdo.option.ConnectionUserName</name><value>root</value></property>
          <property>
            <name>hive.metastore.warehouse.dir</name>
            <value>/app/hive/warehouse</value>
          </property>

        </configuration>


