apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-cfg
  labels:
    app: hive
data:
  hive-env.sh: |
    # Set Hive and Hadoop environment variables here. These variables can be used
    # to control the execution of Hive. It should be used by admins to configure
    # the Hive installation (so that users do not have to set environment variables
    # or set command line parameters to get correct behavior).
    #
    # The hive service being invoked (CLI etc.) is available via the environment
    # variable SERVICE
  
  
    # Hive Client memory usage can be an issue if a large number of clients
    # are running at the same time. The flags below have been useful in
    # reducing memory usage:
    #
    # if [ "$SERVICE" = "cli" ]; then
    #   if [ -z "$DEBUG" ]; then
    #     export HADOOP_OPTS="$HADOOP_OPTS -XX:NewRatio=12 -Xms10m -XX:MaxHeapFreeRatio=40 -XX:MinHeapFreeRatio=15 -XX:+UseParNewGC -XX:-UseGCOverheadLimit"
    #   else
    #     export HADOOP_OPTS="$HADOOP_OPTS -XX:NewRatio=12 -Xms10m -XX:MaxHeapFreeRatio=40 -XX:MinHeapFreeRatio=15 -XX:-UseGCOverheadLimit"
    #   fi
    # fi
  
    # The heap size of the jvm stared by hive shell script can be controlled via:
    #
    # export HADOOP_HEAPSIZE=1024
    #
    # Larger heap size may be required when running queries over large number of files or partitions.
    # By default hive shell scripts use a heap size of 256 (MB).  Larger heap size would also be
    # appropriate for hive server.
  
  
    # Set HADOOP_HOME to point to a specific hadoop install directory
    # HADOOP_HOME=${bin}/../../hadoop
  
    # Hive Configuration Directory can be controlled by:
    # export HIVE_CONF_DIR=
  
    # Folder containing extra libraries required for hive compilation/execution can be controlled by:
    # export HIVE_AUX_JARS_PATH=
  
    # metastore服务器开启jmx监控
    if [ "$SERVICE" = "metastore" ]; then
      JMX_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=8003"
      export HIVE_METASTORE_HADOOP_OPTS="$HIVE_METASTORE_HADOOP_OPTS $JMX_OPTS"
    fi
    

  core-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
      <property>
            <name>fs.defaultFS</name>
            <value>jfs://myjfs</value>
        </property>
       <property>
          <name>fs.jfs.impl</name>
          <value>io.juicefs.JuiceFileSystem</value>
      </property>
      <property>
          <name>fs.AbstractFileSystem.jfs.impl</name>
          <value>io.juicefs.JuiceFS</value>
      </property>
      <property>
          <name>juicefs.meta</name>
          <value>mysql://root:bigdata@(10.81.17.8:33066)/juicefs_k8s</value>
      </property>
      <property>
          <name>juicefs.cache-size</name>
          <value>1024</value>
      </property>
      <property>
          <name>juicefs.access-log</name>
          <value>/tmp/juicefs.access.log</value>
      </property>
      <property>
          <name>juicefs.cache-dir</name>
          <value>/tmp/data/juicefs</value>
      </property>

      </configuration>

  hive-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
        <configuration>

          <property><name>hive.metastore.uris</name><value>thrift://hive-metastore-service:9083</value></property>
          <property><name>datanucleus.autoCreateSchema</name><value>false</value></property>
          <property><name>javax.jdo.option.ConnectionURL</name><value>jdbc:mysql://10.81.17.8:33066/hive2_3_9_k8s?createDatabaseIfNotExist=true&amp;useUnicode=true&amp;characterEncoding=utf8&amp;useSSL=false&amp;rewriteBatchedStatements=true&amp;serverTimezone=Asia/Shanghai</value></property>
          <property><name>javax.jdo.option.ConnectionDriverName</name><value>com.mysql.jdbc.Driver</value></property>
          <property><name>javax.jdo.option.ConnectionPassword</name><value>bigdata</value></property>
          <property><name>javax.jdo.option.ConnectionUserName</name><value>root</value></property>
          <property>
            <name>hive.metastore.warehouse.dir</name>
            <value>/app/hive/warehouse</value>
          </property>
        <property>
            <name>hive.metastore.authorization.storage.checks</name>
            <value>false</value>
        </property>
        
        <property>
            <name>hive.metastore.cache.pinobjtypes</name>
            <value>Table,Database,Type,FieldSchema,Order</value>
        </property>
        
        <property>
            <name>hive.metastore.client.connect.retry.delay</name>
            <value>5s</value>
        </property>
        
        <property>
            <name>hive.metastore.client.socket.timeout</name>
            <value>1800s</value>
        </property>
        
        <property>
            <name>hive.metastore.connect.retries</name>
            <value>24</value>
        </property>
        
        <property>
            <name>hive.metastore.execute.setugi</name>
            <value>true</value>
        </property>
        
        <property>
            <name>hive.metastore.failure.retries</name>
            <value>24</value>
        </property>
        <property>
            <name>hive.metastore.sasl.enabled</name>
            <value>false</value>
        </property>
        
        <property>
            <name>hive.metastore.schema.verification</name>
            <value>false</value>
        </property>
        
        <property>
            <name>hive.metastore.server.max.threads</name>
            <value>100000</value>
        </property>
        
        <!-- 开启hiveserver2服务metrics -->
        <property>
            <name>hive.server2.metrics.enabled</name>
            <value>false</value>
        </property>
        <!-- 开启metastore服务metrics -->
        <property>
          <name>hive.metastore.metrics.enabled</name>
          <value>true</value>
        </property>
        <!-- 可使用默认值，无需修改 -->
        <property>
          <name>hive.service.metrics.class</name>
          <value>org.apache.hadoop.hive.common.metrics.metrics2.CodahaleMetrics</value>
        </property>
        <!-- 可使用默认值，无需修改 -->
        <property>
          <name>hive.service.metrics.reporter</name>
          <value>JSON_FILE, JMX</value>
        </property>

        </configuration>
      
      
